version: '3'
services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:12.3-alpine
    container_name: kong-db
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  #######################################
  # Kong database migration
  #######################################
  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap && kong migrations up && kong migrations finish
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    networks:
      - kong-net
    restart: on-failure

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    container_name: kong-api-gateway
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_LISTEN: 0.0.0.0:9080 http2
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:9081 http2 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    networks:
      - kong-net
    ports:
      - "8000:8000" # http Proxy
      - "8001:8001" # Admin API
      - "9080:9080" # http2 proxy
      - "9081:9081" # http2 SSL proxy
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
      

  #######################################
  # Cassandra service
  #######################################
  cassandra-node1:
    image: cassandra:3.11.6
    container_name: cassandra-service
    # Network for the nodes to communicate
    networks:
       - kong-net
    # volumes
    volumes:
       - ./cassandra_data:/var/lib/cassandra
    # Docker constainer environment variable
    environment:
       - CASSANDRA_CLUSTER_NAME=Test Cluster
       - CASSANDRA_SEEDS=cassandra-node1
       - CASSANDRA_PASSWORD_SEEDER=yes
       - CASSANDRA_PASSWORD=password
    # Exposing ports for inter cluste communication
    expose:
       - 7000  # JMX
       - 7001  # cluster communication
       - 7199  # cluster communication (SSL)
       - 9042  # native protocol clients
       - 9160  # thrift clients
    # ports
    ports:
       - "9042:9042"
    # Restart policy
    restart: always
    # Cassandra ulimt recommended settings
    ulimits:
       memlock: -1
       nproc: 32768
       nofile: 100000



 #######################################
 #  product-service    
 #######################################
  product-service:
    image: product-service:1
    container_name: product-service
    build: ./product-service
    ports: 
       - 60060:60060
    restart: on-failure
    depends_on:
       - cassandra-node1
    networks:
       - kong-net


  #######################################      
  #  customer-service  
  #######################################  
  customer-service:
    image: customer-service:1
    container_name: customer-service
    build: ./customer-service
    ports: 
       - "60061:60061"
    restart: on-failure
    depends_on:
       - cassandra-node1
    networks:
       - kong-net

  #######################################      
  #  payment-service    
  #######################################
  payment-service:
    image: payment-service:1
    container_name: payment-service
    build: ./payment-service
    ports: 
       - 60062:60062
    restart: on-failure
    depends_on:
       - cassandra-node1
    networks:
       - kong-net


  #######################################      
  #  order-service 
  #######################################   
  order-service:
    image: order-service:1
    container_name: order-service
    build: ./order-service
    ports: 
       - "60063:60063"
    restart: on-failure
    depends_on:
       - cassandra-node1
    networks:
       - kong-net

  #######################################      
  # grpc-gateway service
  #######################################
  grpc-gateway:
    image: grpc-gateway:1
    container_name: grpc-gateway
    build: ./grpc-gateway
    ports: 
       - "8081:8081"
    restart: on-failure
    depends_on:
       - product-service
       - customer-service
       - payment-service
       - order-service
    networks:
       - kong-net

##############################################################################       
# Networks to be created to facilitate communication between containers
##############################################################################
networks:
   kong-net:
      driver: bridge
